build:
    image: python:2.7
    commands:
        - pip install -r requirements.txt
publish:
    docker:
        username: projectweekend
        password: $$DOCKER_PASS
        email: $$DOCKER_EMAIL
        repo: projectweekend/thpl-data-logger
        when:
            branch: master
deploy:
    fabric:
        image: projectweekend/drone-fabric
        commands:
            - --user=$$DEPLOY_USER --password=$$DEPLOY_PASSWORD --hosts=$$DEPLOY_HOST deploy
        when:
            branch: master
